name: pytest

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: "cd static && npm ci"
    - run: "cd static && npm run build"
    - name: Archive static assets
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: static/dist

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Fetch built assets
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: static/dist
    - name: Coverage with pytest
      run: |
        coverage run -m pytest
        coverage report -m
      env:
        DATABASE_URL: "sqlite:///db.sqlite"
        DEBUG: True
