name: cookiecutter

on: [ push, pull_request ]

jobs:
  archive:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter
    - name: Cookiecutter
      run: cookiecutter --no-input .
    - name: Archive example
      uses: actions/upload-artifact@v2
      with:
        name: starly
        path: starly
